/*
import { convertTransaction } from '../../converters'

describe('convertTransaction', () => {
  it.each([
    [
      {
        actions: ['sendCheck', 'print', 'toFavorite', 'repeatable'], // По моему эти не надо обрабатывать
        amount: 10000,
        'another-person-payment': null,
        bankSystemId: null,
        bonusAmount: null,
        category: { id: 394010367, name: 'Переводы' },
        charge: '2020-08-22T17:24:19+05:00',
        comment: null,
        controlValue: null,
        convAmount: null,
        convCurrency: null,
        counterpartyId: null,
        'create-date': '2020-08-22T17:23:49+05:00',
        currency: 'RUB',
        data_contacts: { 'always-notify': false, 'counterparty-notify': false },
        dateCreated: '2020-08-22T17:23:49+05:00',
        'debtor-city': null,
        'debtor-flat': null,
        'debtor-house': null,
        'debtor-inn': null,
        'debtor-kpp': null,
        'debtor-lastname': null,
        'debtor-middlename': null,
        'debtor-name': null,
        'debtor-nonResident': null,
        'debtor-street': null,
        'debtor-type': null,
        direction: 'debit',
        ekassir: false,
        feeAmount: 0,
        feeCurrency: 'RUB',
        fields: {},
        firstCurrency: null,
        icon:
          {
            hash: '1a751336e99fa57c3295ab785571db69',
            url: '/imgcache/bankData628293674_1a751336e99fa57c3295ab785571db69.png'
          },
        internalCode: null,
        kvvo: null,
        limit: null,
        linked_document_id: null,
        linked_document_type: null,
        mainRequisite: 'С карты ****4617',
        nds: 0,
        ndsType: null,
        operationDescription: 'В "СКБ-Банк" на карту ***6004',
        operationIcon: 'https://ib.delo.ru/imgcache/bankIcon_ii312846246.png',
        'order-date': '2020-08-22',
        orderedRequisites: [{ name: 'Банк получателя', value: 'СКБ-Банк' }],
        originalRegistry: null,
        outdated: false,
        'payee-account': null,
        'payee-bank-account': null,
        'payee-bank-bic': null,
        'payee-bank-name': null,
        'payee-card': '170537804',
        'payee-card-id': null,
        'payee-card-mask-pan': '548386******6004',
        'payee-inn': null,
        'payee-kpp': null,
        'payee-member-id': null,
        'payee-name': null,
        'payee-phone': null,
        'payer-account': null,
        'payer-bank-account': null,
        'payer-bank-bic': null,
        'payer-bank-name': null,
        'payer-card': '170971097',
        'payer-card-mask-pan': '427681******4617',
        'payer-inn': null,
        'payer-kpp': null,
        'payment-date': null,
        'payment-kind': null,
        'payment-number': '142',
        'payment-operation-type': 'externalPayment',
        'payment-type': null,
        payout: null,
        'payout.date': null,
        'payout.type': null,
        pointOfInitiationMethod: null,
        priority: '5',
        productAccount: null,
        productCardId: 170971097,
        productDescription: 'Сбербанк',
        productType: 'С карты',
        profit: null,
        purpose: 'Перевод с карты на карту',
        purposeCode: null,
        qrIdentifier: null,
        rate: null,
        reason: null,
        registryPaidAmount: null,
        relatedRegistryPayment: false,
        requisites: { 'Банк получателя': 'СКБ-Банк' },
        'rest-amount': null,
        revokeRejectReason: null,
        secondCurrency: 'RUB',
        skbPaymentOperationType: 'p2p',
        state: 'processed',
        'tax-101': null,
        'tax-104': null,
        'tax-105': null,
        'tax-106': null,
        'tax-107': null,
        'tax-108': null,
        'tax-109': null,
        'tax-110': null,
        uin: null,
        'zhkkh.communalPayment': null,
        'zhkkh.consumerApartment': null,
        'zhkkh.consumerInn': null,
        'zhkkh.consumerMName': null,
        'zhkkh.consumerName': null,
        'zhkkh.consumerPlacement': null,
        'zhkkh.consumerSName': null,
        'zhkkh.documentId': null,
        'zhkkh.fiasCode': null,
        'zhkkh.payDate': null,
        'zhkkh.perfDocNumber': null,
        'zhkkh.personalAccount': null,
        'zhkkh.singlePersonalAcc': null,
        'zhkkh.type': null
      },
      {
        date: '2020-08-22T17:23:19+05:00',
        hold: false,
        comment: 'С карты ***4617',
        merchant: {
          country: null,
          city: null,
          title: 'В "СКБ-Банк" на карту ***6004',
          mcc: null,
          location: null
        },
        movements: [
          {
            id: '855984970',
            account: { id: 'account' },
            invoice: null,
            sum: 10000,
            fee: 0
          },
          {
            id: null,
            account: {
              type: null,
              instrument: 'RUB',
              syncIds: ['40817810100015387612'],
              company: null
            },
            invoice: null,
            sum: -10000.00,
            fee: 0
          }
        ]
      }
    ]
  ])('should convert Card transfer', (rawTransaction, transaction) => {
    const accounts = { id: 'account', instrument: 'RUB' }
    expect(convertTransaction(accounts, rawTransaction)).toEqual(transaction)
  })
})

 */
