import { convertAccounts } from '../../converters'

describe('convertAccounts', () => {
  it.each([
    [
      {
        accounts:
          [
            {
              id: 170522760,
              customName: false,
              name: 'Счет Mastercard Unembossed',
              productName: 'Счет Mastercard Unembossed',
              number: '40817810000015511074',
              state: 'Открыт',
              stateCode: 'open',
              amount: 7302.49,
              type: 'card',
              registryAmount: 0,
              registry2Amount: 0,
              balance: 36063.61,
              currency: 'RUB',
              availableBalance: 7302.49,
              availBalanceRub: 7302.49,
              startDate: '11.05.2019',
              order: 1,
              category: 'account',
              requisites:
                {
                  bankName: 'ФИЛИАЛ "ВОЛЖСКИЙ" ПАО "СКБ-БАНК"',
                  address: 'Россия, 400066, Волгоградская обл, Волгоград г, Коммунистическая ул, д.16',
                  bic: '041856890',
                  inn: '6608003052',
                  kpp: '343503001',
                  corrAccount: '30101810800000000890'
                },
              allowInPayments: true,
              allowOutPayments: true,
              allowLoanRepayment: true,
              tariffPlanName: 'Универсальный',
              tariffPlanCode: '',
              tariffPlanLinkToRules: '',
              specType: 'EX',
              mostActive: false,
              pdfLink: '/export/account/pdf?id=170522760',
              overdraft: false,
              sbpDefault: false,
              bonusProgramState: 'enabled',
              availableBonuses: 297.36,
              accruedBonuses: 425.22,
              nextAccrualDate: '2020-09-01',
              lockedAmount: 0,
              canClose: true,
              bonusProgramGroup:
                {
                  firstCategory: '3',
                  secondCategory: '3',
                  thirdCategory: '3',
                  selectCategoryDate: '2020-07-06T13:03:43.000+0500'
                },
              petitionId: null,
              tariffPlanCanChange: false,
              cards: [170537804, 310720201]
            },
            {
              id: 42424242,
              customName: false,
              name: 'Счет RUB',
              productName: 'Счет RUB',
              number: '40817810900087654321',
              state: 'Открыт',
              stateCode: 'open',
              amount: 1000.00,
              type: 'current',
              registryAmount: 0,
              registry2Amount: 0,
              balance: 1000.00,
              currency: 'RUB',
              availableBalance: 1000.00,
              availBalanceRub: 1000.00,
              startDate: '08.08.2020',
              order: 99,
              category: 'account',
              requisites: {
                bankName: 'ФИЛИАЛ "МОСКОВСКИЙ" ПАО "СКБ-БАНК"',
                address: 'Россия, 109004, Москва г, Москва г, Николоямская ул, д.40/22, корп.4',
                bic: '044520000',
                inn: '',
                kpp: '775002001',
                corrAccount: '30101810045250000472'
              },
              allowInPayments: true,
              allowOutPayments: true,
              allowLoanRepayment: true,
              tariffPlanName: 'Универсальный',
              tariffPlanCode: '',
              tariffPlanLinkToRules: '',
              specType: 'EX',
              mostActive: false,
              pdfLink: '/export/account/pdf?id=42424242',
              overdraft: false,
              sbpDefault: false,
              bonusProgramState: 'forbidden',
              availableBonuses: 0,
              accruedBonuses: 0,
              nextAccrualDate: null,
              lockedAmount: 0,
              canClose: true,
              bonusProgramGroup: {
                firstCategory: '0',
                secondCategory: '0',
                thirdCategory: '0',
                selectCategoryDate: null
              },
              petitionId: 850361797
            },
            {
              id: 40681777,
              customName: false,
              name: 'Счет RUB',
              productName: 'Счет RUB',
              number: '40817810239923082636',
              state: 'Открыт',
              stateCode: 'open',
              amount: 0,
              type: 'current',
              registryAmount: 0,
              registry2Amount: 0,
              balance: 0,
              currency: 'RUB',
              availableBalance: 0,
              availBalanceRub: 0,
              startDate: '13.03.2014',
              order: 1,
              category: 'account',
              requisites:
                {
                  bankName: 'ФИЛИАЛ "ВОЛОГОДСКИЙ" ПАО "СКБ-БАНК"',
                  address: 'Россия, 190031, Санкт-Петербург г, Московский пр-кт, д.2, корп.6, кв.77Н, лит.А',
                  bic: '041909781',
                  inn: '6608003052',
                  kpp: '352543001',
                  corrAccount: '30101810300000000781'
                },
              allowInPayments: true,
              allowOutPayments: true,
              allowLoanRepayment: false,
              tariffPlanName: 'Стандартный',
              tariffPlanCode: '',
              tariffPlanLinkToRules: '',
              specType: 'EP',
              mostActive: false,
              pdfLink: '/export/account/pdf?id=40681777',
              overdraft: false,
              sbpDefault: false,
              bonusProgramState: 'forbidden',
              availableBonuses: 0,
              accruedBonuses: 0,
              nextAccrualDate: null,
              lockedAmount: 0,
              canClose: false,
              bonusProgramGroup:
                {
                  firstCategory: '0',
                  secondCategory: '0',
                  thirdCategory: '0',
                  selectCategoryDate: null
                },
              petitionId: null,
              tariffPlanCanChange: false
            }
          ],
        cards:
          [
            {
              id: '4136158',
              state_description: 'Действующая',
              blocked: false,
              name: 'Mastercard Unembossed',
              customName: false,
              amount: 7302.49,
              currency: 'RUB',
              pan: '548386******6004',
              cardholderName: '',
              category: 'card',
              expDate: '2023-10-31',
              balance: 36063.61,
              availableBalance: 7302.49,
              holdAmount: 28761.12,
              primaryAccount: '40817810000015511074',
              accountId: 170522760,
              tariffLink: 'https://www.skbbank.ru/chastnym-licam/karty/icard',
              order: '1',
              primary: true,
              cardId: '4136158',
              brand: 'Mastercard Unembossed',
              storedId: 170537804,
              limits: [],
              status: '00',
              status_desc: 'Карта не блокирована',
              state: '2',
              kind: 'debit',
              loan_funds: 0,
              own_funds: 7302.49,
              used_loan_funds: 0,
              most_active: false,
              smsPhone: '79033164152',
              smsType: null,
              packageCashBack: 'forbidden',
              packageFreeCashOut: 'off',
              packageServ: false,
              paymentSystem: 'MC',
              limit_set_available: false,
              own_customer_card: true,
              holder_name: 'Иванов Иван Иванович',
              design_id: '23006',
              design_front_url: '/export/card/design?code=23006&side=front',
              design_back_url: '/export/card/design?code=23006&side=back',
              textColor: 'white',
              canUnlock: false,
              canReissue: false,
              canAddCard: false,
              contactless: true,
              smsNotify: 30,
              highCashBack: 30,
              freeWithdraw: 30,
              canViewCvv2: false,
              smsService: false,
              canIssuePlastic: false
            },
            {
              id: '4136158', // Вторая карта на один лицевой счет. Как правильно жолжны быть заполнены поля ???
              state_description: 'Действующая',
              blocked: false,
              name: 'Mastercard Unembossed',
              customName: false,
              amount: 7302.49,
              currency: 'RUB',
              pan: '123456******7890',
              cardholderName: '',
              category: 'card',
              expDate: '2023-10-31',
              balance: 36063.61,
              availableBalance: 7302.49,
              holdAmount: 28761.12,
              primaryAccount: '40817810000015511074',
              accountId: 170522760,
              tariffLink: 'https://www.skbbank.ru/chastnym-licam/karty/icard',
              order: '1',
              primary: true,
              cardId: '4136158',
              brand: 'Mastercard Unembossed',
              storedId: 310720201,
              limits: [],
              status: '00',
              status_desc: 'Карта не блокирована',
              state: '2',
              kind: 'debit',
              loan_funds: 0,
              own_funds: 7302.49,
              used_loan_funds: 0,
              most_active: false,
              smsPhone: '79033164152',
              smsType: null,
              packageCashBack: 'forbidden',
              packageFreeCashOut: 'off',
              packageServ: false,
              paymentSystem: 'MC',
              limit_set_available: false,
              own_customer_card: true,
              holder_name: 'Иванов Иван Иванович',
              design_id: '23006',
              design_front_url: '/export/card/design?code=23006&side=front',
              design_back_url: '/export/card/design?code=23006&side=back',
              textColor: 'white',
              canUnlock: false,
              canReissue: false,
              canAddCard: false,
              contactless: true,
              smsNotify: 30,
              highCashBack: 30,
              freeWithdraw: 30,
              canViewCvv2: false,
              smsService: false,
              canIssuePlastic: false
            }
          ],
        loans:
          [
            {
              id: 40681781,
              bank_system_id: '9625620',
              productName: 'Персональное предложение (потребительский кредит)',
              productCode: '1292',
              customName: true,
              name: 'ПЕРСОНАЛЬНОЕ ПРЕДЛОЖЕНИЕ (потребительский кредит)',
              amount: 216300,
              currency: 'RUB',
              interestRate: 26.9,
              psk: 22.924,
              contractDate: '13.03.2014',
              contractNumber: '39913394134',
              openDate: '13.03.2014',
              endDate: '13.11.2023',
              allowPaymentAmount: 20878.61,
              partialPaymentDate: '14.09.2020',
              planPaymentAmount: 5900,
              mainAccount: '45507810939900624978',
              repaymentAccount: '40817810239923082636',
              recommendedPaymentAmount: 5900,
              partialPaymentAmount: null,
              prepayment: false,
              overdueDebtAmount: 0,
              overdraft: false,
              startPaymentPeriod: null,
              gracePeriodDate: null,
              creditLimit: null,
              availableLimit: null,
              prepaymentApplication: false,
              changeDate: false,
              ownFounds: null,
              changeRepaymentAccount: false,
              partialPaymentMarker: false,
              reduceLimit: false,
              closeLimit: false,
              prepaymentAmount: null,
              prepaymentId: null,
              prepaymentType: null,
              loanHolder: 'ПАО "СКБ-банк"',
              paymentsDelay: true,
              paymentsDelayId: null,
              scheduleChanged: false,
              mortgage: false,
              onlineRepayment: false,
              petitionId: null,
              minLimit: null
            }
          ],
        deposits:
          [
            {
              id: 850348772,
              bank_system_id: '16748162',
              contract_number: '30016740929',
              contract_date: '08.08.2020',
              close_account: '40817810700012345678',
              capitalization: true,
              currency: 'RUB',
              opening_balance: 10000.00,
              min_balance: 10000.00,
              balance: 10000.00,
              percentPaidPeriod: 'В конце срока',
              duration: '270',
              open_date: '08.08.2020',
              end_date: '05.05.2021',
              early_close: true,
              rate: 5.2000,
              ratePeriods: [],
              balanceRub: 10000.00,
              account: '42305810330000000042',
              branch_id: 69559,
              allow_out_payments: false,
              allow_in_payments: false,
              percent_manageable: false,
              capital_manageable: false,
              percent_account: '42305810330000000042',
              auto_prolongation: false,
              state: 'open',
              state_description: 'Действующий',
              customName: false,
              name: 'Исполнение желаний + (срочный вклад)',
              productName: 'Исполнение желаний + (срочный вклад)',
              percent_paid: 0.00,
              percent_accrued: 0.00,
              requisites: {
                bankName: 'ФИЛИАЛ "МОСКОВСКИЙ" ПАО "СКБ-БАНК"',
                address: 'Россия, 109004, Москва г, Москва г, Николоямская ул, д.40/22, корп.4',
                bic: '044520000',
                inn: '',
                kpp: '775002001',
                corrAccount: '30101810045250000472'
              },
              petitionId: 850348751,
              interestType: null,
              charity: 'forbidden'
            }
          ]
      },
      [
        {
          id: '40817810000015511074',
          type: 'ccard',
          title: 'Счет Mastercard Unembossed',
          instrument: 'RUB',
          balance: 7302.49,
          creditLimit: 0,
          syncIds: [
            '40817810000015511074',
            '548386******6004',
            '123456******7890'
          ],
          storedId: [170537804, 310720201]
        },
        {
          id: '40817810900087654321',
          type: 'checking',
          title: 'Счет RUB',
          instrument: 'RUB',
          balance: 1000.00,
          creditLimit: 0,
          syncIds: ['40817810900087654321']
        },
        {
          id: '40817810239923082636',
          mainAccount: '45507810939900624978',
          type: 'loan',
          title: 'ПЕРСОНАЛЬНОЕ ПРЕДЛОЖЕНИЕ (потребительский кредит)',
          instrument: 'RUB',
          balance: -216300,
          capitalization: true,
          percent: 26.9,
          startDate: new Date('2014-03-12T20:00:00.000Z'),
          endDateOffset: 116,
          endDateOffsetInterval: 'month',
          syncIds: [
            '45507810939900624978',
            '40817810239923082636'
          ]
        },
        {
          id: '42305810330000000042',
          type: 'deposit',
          title: 'Исполнение желаний + (срочный вклад)',
          instrument: 'RUB',
          balance: 10000,
          capitalization: true,
          percent: 5.2,
          startDate: new Date('2020-08-07T21:00:00.000Z'),
          startBalance: 10000,
          payoffInterval: null,
          payoffStep: 0,
          endDateOffset: 270,
          endDateOffsetInterval: 'day',
          syncIds: ['42305810330000000042']
        }
      ]
    ]
  ])('converts Full accounts', (apiAccounts, accounts) => {
    expect(convertAccounts(apiAccounts)).toEqual(accounts)
  })
})
